fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [ commit ]
        language: system
        entry: poetry run black
        types: [ python ]

      - id: ruff
        name: ruff
        stages: [commit]
        language: system
        entry: poetry run ruff --fix --show-fixes
        types: [python]
